site_name: Doc SAP
site_author: Antoine Dupont
site_description: >-
  Doc SAP est un site de documentation permettant de partager du code, astuces,
  et autres informations utiles quant à l'utilisation du progiciel.

nav:
  - Home: index.md
  - Créer une page: documentation.md


theme:
  name: material
  icon: 
    logo: material/code-brackets
  features: 
    - navigation.instant # clicks on all internal links will be intercepted and dispatched via XHR without fully reloading the page
    - navigation.instant.prefetch # start to fetch a page once the user hovers over a link
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.path # breadcrumb navigation is rendered above the title of each page
    - navigation.footer

    - search.suggest # the search will display the likeliest completion for the last word
    - search.highlight
    - search.share

    - header.autohide

    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - content.tabs.link

  language: en
  
  palette:
    scheme: sap
    accent: sap
    # - scheme: default
    #   primary: amber
    #   accent: orange
    #   toggle:
    #     icon: material/toggle-switch-off-outline
    #     name: Switch to sombre mode
    # - scheme: slate
    #   primary: amber
    #   accent: orange
    #   toggle:
    #     icon: material/toggle-switch
    #     name: Switch to clair mode
  
  font:
    text: Roboto
    code: Roboto Mono

  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/light-bulb-24
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

plugins:
  - search
  - social

extra_css:
  - stylesheet/extra.css

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/BoBsmil3Y
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/watch?v=2RlTqFtdlH8

copyright: |
  Mis en place par <a href="https://github.com/BoBsmil3Y" target="_blank">Antoine Dupont</a> avec <a href="https://www.mkdocs.org/" target="_blank">MkDocs</a>. Thème : <a href="https://github.com/squidfunk/mkdocs-material" target="_blank">Material</a>

markdown_extensions:
  - attr_list
  - admonition
  - md_in_html
  - pymdownx.details            # supercharges the Admonition extension, making the resulting call-outs collapsible
  - pymdownx.inlinehilite       # add support for syntax highlighting of inline code blocks
  - pymdownx.superfences       # allows for arbitrary nesting of code and content blocks inside each other
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  - pymdownx.emoji:             #  automatically inlines bundled and custom icons and emojis
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  
  - pymdownx.highlight:         # adds support for syntax highlighting of code blocks
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  
  - pymdownx.tabbed:            # enables content tabs
      alternate_style: true